apiVersion: v1
kind: Service
metadata:
  labels:
    name: reactcomponents
  name: reactcomponents
spec:
  ports:
    - protocol: "TCP"
      port: 5100
      targetPort: 3000
  selector:
    app: reactcomponents
